services:
  - type: web
    name: frontend-farmacia
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://backend-farmacia.onrender.com
      - key: PORT
        value: 10000